name: broshet
favicon: null
layout_spectrum: 0.02389849186874926
typography_spectrum: 0.16008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2c489'
    - '#64210e'
    - '#eb8875'
    - '#391509'
    - '#a6592f'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
